[1mdiff --git a/index.html b/index.html[m
[1mindex 313323d..9853e53 100644[m
[1m--- a/index.html[m
[1m+++ b/index.html[m
[36m@@ -1,3 +1,4 @@[m
 <h1>This is my new repo</h1>[m
[31m-<p>This is a new feature1</p>[m
[31m-<h1>welcome</h1>[m
\ No newline at end of file[m
[32m+[m[32m<p>This is a new feature</p>[m
[32m+[m[32m<p>This is new future(button)</p>[m
[32m+[m[32m<p>welcome guys</p>[m
